#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-DeepThoughts
version:      0.01
version_from: lib/Acme/DeepThoughts.pm
installdirs:  site
requires:
    Text::Wrap:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
